[tool.briefcase]
author = 'Jimmy Girardet'
author_email = "ijkl@netc.fr"
bundle = "coding.cacahuete"
license = "GNU General Public License v3 (GPLv3)"
project_name = "mydevoirs"
url = "https://jgirardet.github.io/mydevoirs"
version = "1.2.0"

[tool.briefcase.app.mydevoirs]
description = "La prise de devoirs enfin simple !"
formal_name = "mydevoirs"
icon = "mydevoirs/data/icons/logo"
requires = [
  'kivy',
  'pony>=0.7.11,<0.8',
  'appdirs',
  'kivy-garden.filebrowser',
  'Pillow',
]
sources = ['mydevoirs']

[tool.briefcase.app.mydevoirs.macOS]
requires = []

[tool.briefcase.app.mydevoirs.linux]
requires = []
system_requires = ["language-pack-fr", "pulseaudio", "libmtdev1", "xclip", "libgl1", "libfontconfig1", "libxrender1"]

[tool.briefcase.app.mydevoirs.windows]
requires = ["docutils", "pygments", "pypiwin32", "kivy.deps.sdl2", "kivy.deps.glew", "kivy_deps.angle"]

# Mobile deployments
[tool.briefcase.app.mydevoirs.iOS]
requires = []

[tool.briefcase.app.mydevoirs.android]
requires = []

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true
